WIDTH = 800
HEIGHT = 600
BLUE_PARTICLE_COUNT = 500
WHITE_RADIUS = 15
BLUE_RADIUS = 7
RANDOM_VELOCITY_RANGE = 10
FRAME_DELAY_MS = 16
TRAIL_LENGTH = 200
BG_COLOR = "#0a0a19"
BLUE_COLOR = "#48bcfa"
TRAIL_COLOR = "#6464ff"

RED_RADIUS = 12
RED_COLOR = '#ff4040'
RED_TRAIL_COLOR = '#ff9900'

# --- visual effects ---
TRAIL_FADE = True
GLOW_RINGS = 4
GLOW_SPREAD = 0.6      # how far each ring grows past radius
GLOW_ENABLED = False
EASE = 0.15            # 0..1, higher = snappier

